name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_REPOSITORY || 'ecommerce-platform' }}
  SERVICES_DIR: ./services  # Добавляем переменную для пути к сервисам

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build all services
      run: |
        cd ${{ env.SERVICES_DIR }}/api-gateway && ./gradlew build
        cd ${{ env.SERVICES_DIR }}/auth-service && ./gradlew build
        cd ${{ env.SERVICES_DIR }}/user-service && ./gradlew build
      
    - name: Run tests
      run: |
        cd ${{ env.SERVICES_DIR }}/api-gateway && ./gradlew test
        cd ${{ env.SERVICES_DIR }}/auth-service && ./gradlew test
        cd ${{ env.SERVICES_DIR }}/user-service && ./gradlew test
      
    - name: Upload code coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-reports
        path: |
          ${{ env.SERVICES_DIR }}/api-gateway/build/reports/jacoco/test/html/
          ${{ env.SERVICES_DIR }}/auth-service/build/reports/jacoco/test/html/
          ${{ env.SERVICES_DIR }}/user-service/build/reports/jacoco/test/html/
        retention-days: 7

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push API Gateway
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.SERVICES_DIR }}/api-gateway
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}-api-gateway:latest
    
    - name: Build and push Auth Service
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.SERVICES_DIR }}/auth-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}-auth-service:latest
    
    - name: Build and push User Service
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.SERVICES_DIR }}/user-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}-user-service:latest
